### ISSUE TITLE
Commas cause GPUDrivers throw ValueError

### ISSUE THREAD

**Issue by zvonimirfras** [loherangrin/o3tanks#27]
https://github.com/loherangrin/o3tanks/blob/dc7d7871bc06096905563f91ad996d3287e48a7e/recipes/o3tanks/globals/o3tanks.py#L71-L76

Lines 72, 74, 75

Removing them solves it and returns the expected values.

**Comment by loherangrin** [comment]
I added the fix within the implementation of #28 , which is going to be released.
I'll close this issue when I merge the PR.
