### ISSUE TITLE
Unbound variable DOCKER_HOST

### ISSUE THREAD

**Issue by VencaCZ** [loherangrin/o3tanks#55]
On line 921 we have this

`if [ -n "${DOCKER_HOST}" ]; then`

but since we we are under **set -eu** this will end our script instead of going for false path.

Simple way how to fix this would be:

`if [ -n "${DOCKER_HOST+x}" ]; then`

**Comment by loherangrin** [comment]
Thanks, I missed the default initialization. I will add it to the cumulative PR with the other improvements of error messages.
