### ISSUE TITLE
Command not found while installing engine

### ISSUE THREAD

**Issue by VencaCZ** [loherangrin/o3tanks#58]
After running
```
o3tanks install engine --branch development
```
It finishes with
```
Please run the following commands (or use your preferred GIT client):
cd /var/lib/docker/volumes/o3tanks-source_development/_data
git lfs install
git lfs pull

Then, resume the current operation using:
o3tanks install engine --force development
```
but when you try to run command mentioned at the end you will get 
```
o3tanks: error: unrecognized arguments: development
```

If you try yo run original command again there will be a new error
```
ERROR: Engine version 'development' is already installed with a different build workflow (Project / Source)
```

**Comment by loherangrin** [comment]
The command is missing the parameter name identifying the origin (`--branch`) that you want to clone. From what you have used before, it should be:
```
o3tanks install engine --branch development --force
```

I will fix it in PR related to issue #56, since I think that the last message can be improved further too.
